#+TITLE: Git CheatSheet
#+AUTHOR: Joshua Branson

* Introduction
  Linus Torvalds created git to remind you how stupid you are.  In fact "git" is British slang for idiot.

  It's syntax looks like git <command> [<args>]

  You can always look up help on a specific git command with man git-<command>

** Basic commands

 - push your changes to a remote git repo
   git push

 - pulling your changes from a remote to a local git repo
   git pull

 - pulling changes from a remote repo and discarding your local changes
   git fetch origin
   git reset --hard origin/[master | tag | branch | commit-id ]
 - git rm FILE
   Stop tracking a file.  Notice that these files can still be found in the repo.  Any updates to these files will not be added to the repo, BUT the file can still be found in git.

*** git rm FILE/S
Suppose that you have a file that contains a user's various passwords.  You then mistakenly add that file to the repo, and commit it.

 ~git add passwords.txt~
 ~git commit -m "some commit"\~

You then realize that you want to remove that file from the repo.

~git rm passwords.txt~
~git commit~

BUT the file is still in the repo!  You can still see it in the repo history.
** common tasks
*** Removing a file from git
=git rm -r --cached /path/to/file=

Note that this DOES not delete the file.  It only makes git stop keeping track of it, and it removes it completely from the repo.
To stop git from tracking the file add =/path/to/file= into the =.gitignore= file.
*** git gc
cleans up a git repo.  Tries to automatically purge files in the tree that cannot be accessed anymore.
*** push an existing repo to github

Create a repo on github, and don't add a license or a readme.

Go to the directory where you want to create the git repo:
=git init=
=touch README.md=
=touch license=
=git add README.md=
=git add license=
=git remote add origin https://path/to/your/github/account.git=
=git push -u origin master=
