#+AUTHOR:Joshua Branson
#+TITLE: Kino Wear Bible
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage[QX]{fontenc}
#+OPTIONS: H:10 toc:nil

* Kino Wear Bible

Only buy/wear something if it fits.
avoid logos and images and branding on clothing.  People should have to pay me to wear their brands.
Accessories can be a good way to save money.  A $10 accessory belt can look as good as a $100 one.
Looking better gets you compliments.  People subconsciously respect you more.
  - Just today 2 people complimented my outfit.  One of them was a manly man that I admire a lot!
    [2016-10-03 Mon]
When you are just starting wear a about 3 colors.  Try not to do too many colors.  You might end of looking like a clown.

peach won't work with my skin color
slighter bright blue with bring out my eyes
ties might be hard to wear with Chinos
A streamer will launder my dress shirts and pants
I can wear an under-layer for pants to let it collect sweat

business casual does not necessarily mean tie
dress shirt is measured by neck and length of shirt

regular shirts are small medium and large

is texture good?

a textured tie is good with a non-textured shirt

Try to wear complimentary colors.  Colors on the opposite side of the color spectrum

Being EDGY at work might not be good at Purdue.  They are conservative.
might not be good to wear suit jacket and hoodie
Or suit jacket with jeans.
wash your clothes in the proper way on the label.  They will last longer.


Bottom of page 36.  Good joke.

* does the dress shirt fit?
- collar need to be stiff
- should stitching-needs to align with break of shoulder bone
- shirt should mold to the shape of my chest
- the armpit shouldn't have more than .5 Flatt fabric.
  I think that means that when I lift my arms up, it shouldn't sag
  more than half an inch.
- only one fist can fit between the shirt and my hip.


They get dirty easy.  So perhaps don't spend too much.  Perhaps don't wear
them to parties where you will get all sweaty and dirty.

$200 should be the most that you spend on a shirt.

* jeans raw blue jeans
p. 40
raw denim
blue raw
I can find decent jeans at
Nudie
Acne
Naked and Famous
